# tasks file for ubuntu-1604-apache-mod-php
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_1604_apache_mod_php_dependencies }}"

- name: install | additional
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_1604_apache_mod_php_install }}"
